### ISSUE TITLE
Unable to run Regression model(s) obtained from SES or MMPC

### ISSUE THREAD

**Issue by mariamaseng** [mensxmachina/MXM-R-Package#4]
Hi! I am able to run the MMPC for feature selection, but I am not able to run the regression model.

This works perfectly;
mod = MXM::MMPC(target = y_train, dataset = x_train)
_Length      Class       Mode 
         1 MMPCoutput         S4_ 

Whereas, when using the variable selected for regression I get:
mmpc.model(target = y_train, dataset = x_train, mmpcObject = mod)
**Error in `[.data.frame`(dataset, , i) : undefined columns selected**

Any idea of whay this doesnt work? Thanks for help.
Maria
Btw 1: sorry, not allowed by uni/hospital to post data, so making it impossible to reproduce my trouble here.
Btw 2:
x_train = data.frame
y_train = numeric vector

**Comment by statlink** [comment]
Hi Maria.

Are you sure the "mod" object contains selected variables? I mean, did mmpc() select any variables?

Michail

**Comment by mariamaseng** [comment]
Yes, the mmpc() selected 9 variables
 
> summary(mod)
    _Length      Class       Mode 
         1 MMPCoutput         S4_ 
> mod@selectedVarsOrder
_[1] 100  34  72 101  48  56  78  40  29_

Thanks!

**Comment by statlink** [comment]
Since you cannot share the data tell me the following:

What is the y? continuous, binary, ordinal, what?
What is the test you used? testIndReg, testIndFisher, what?

**Comment by mariamaseng** [comment]
y_train = binary, coded as 0 and 1
x_train = continous

I used the default, testIndFisher, but see now that this likely isnt the best choice so did with testIndNB instead. Still same error.

**Comment by statlink** [comment]
Actually for this case it is testIndLogistic. 

I cannot understand what is going on.  Send me an email at mtsagris@yahoo.gr to discuss this more.

**Comment by mariamaseng** [comment]
Ok, thanks a lot! I will do.
